apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "process-exporter.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "process-exporter.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  config.yaml: |
    process_names:
      {{- toYaml .Values.config.nameMatchers | nindent 6}}
