apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "process-exporter.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "process-exporter.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "process-exporter.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "process-exporter.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
    spec:
      containers:
        - name: process-exporter
          image: "{{- include "common.images.image" ( dict "imageRoot" .Values.image "chart" .Chart) -}}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - --procfs=/host/proc
            - --config.path=/etc/process-exporter/config.yaml
            - "--web.listen-address=0.0.0.0:{{ .Values.service.port }}"
            - "--threads={{ .Values.config.threads }}"
            {{- if .Values.extraArgs }}
            {{- include "common.tplvalues.render" (dict "value" .Values.extraArgs "context" $) | nindent 12 }}
            {{- end }}
          ports:
            - containerPort: {{ .Values.service.port }}
              name: metrics
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: {{ .Values.service.port }}
            initialDelaySeconds: 20
            periodSeconds: 30
            failureThreshold: 3
            successThreshold: 1
          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.service.port }}
            initialDelaySeconds: 20
            periodSeconds: 30
            failureThreshold: 3
            successThreshold: 1
          volumeMounts:
            - name: proc
              mountPath: /host/proc
              readOnly: true
            - name: config
              mountPath: /etc/process-exporter
          {{- if .Values.resources }}
          resources: {{- toYaml .Values.resources | nindent 12 }}
          {{- end }}
          {{- if .Values.securityContext }}
          securityContext: {{- toYaml .Values.securityContext | nindent 12 }}
          {{- end }}
      volumes:
        - name: proc
          hostPath:
            path: /proc
            type: Directory
        - name: config
          configMap:
            name: {{ include "process-exporter.fullname" . }}
      serviceAccountName: {{ include "process-exporter.serviceAccountName" . }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with  .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
