apiVersion: v1
kind: Service
metadata:
  name: {{ include "process-exporter.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "process-exporter.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  selector:
    app.kubernetes.io/name: {{ include "process-exporter.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: metrics
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: metrics
  type: {{ .Values.service.type }}
