name: Lint and Test Charts

on: pull_request

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      changed: ${{ steps.set-output.outputs.changed }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.7.0

      - name: Run chart-testing (list-changed)
        id: set-output
        run: |
          changed=$(ct list-changed --config ct.yaml)
          echo "Changed charts: $changed"
          if [[ -n "$changed" ]]; then
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "changed=false" >> $GITHUB_OUTPUT
          fi
  lint-test:
    needs: detect-changes
    if: needs.detect-changes.outputs.changed == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v4.3.0
        with:
          version: v3.17.1

      # Python is required because `ct lint` runs Yamale (https://github.com/23andMe/Yamale) and
      # yamllint (https://github.com/adrienverge/yamllint) which require Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.7.0

      - name: Run chart-testing (lint)
        run: ct lint --config ct.yaml

      - name: Create kind cluster
        uses: helm/kind-action@v1.12.0

      - name: Deploy Prometheus Operator CRDs
        run: |
          helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
          helm repo update
          helm upgrade --install prometheus-operator-crds prometheus-community/prometheus-operator-crds \
            --namespace default \
            --wait \
            --set alertmanagerconfigs.enabled=false \
            --set alertmanagers.enabled=false \
            --set podmonitors.enabled=false \
            --set probes.enabled=false \
            --set prometheusagents.enabled=false \
            --set prometheuses.enabled=false \
            --set prometheusrules.enabled=false \
            --set scrapeconfigs.enabled=false \
            --set thanosrulers.enabled=false

      - name: Run chart-testing (install)
        run: ct install --config ct.yaml
